package net.sgeht.moleverse.client.render;

import net.minecraft.client.animation.KeyframeAnimation;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.neoforged.neoforge.client.entity.animation.json.AnimationHolder;
import net.sgeht.moleverse.Moleverse;
import net.sgeht.moleverse.debug.MoleDebug;

/**
 * Mole model.
 *
 * <p>The geometry in {@link #createBodyLayer()} is generated: it comes straight
 * from the Blockbench export of {@code art/mole.bbmodel}. Do not edit it by
 * hand, change the model and re-export instead. Only this surrounding class is
 * written by hand, because Blockbench has no export template for this Minecraft
 * version. See {@code docs/MODEL_WORKFLOW.md}.</p>
 */
public class MoleModel extends EntityModel<MoleRenderState> {

    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Moleverse.id("mole"), "main");

    private static final AnimationHolder WALK = getAnimation(Moleverse.id("mole_walk"));
    private static final AnimationHolder PEEK = getAnimation(Moleverse.id("mole_peek"));

    private final KeyframeAnimation walk;
    private final KeyframeAnimation peek;

    /**
     * The bone every other part hangs from. Rotating it aims the whole mole,
     * which is what the rearing pose needs - and what aiming a digging mole in
     * an arbitrary direction will need later.
     */
    private final ModelPart moleRoot;

    public MoleModel(ModelPart root) {
        super(root);
        this.moleRoot = root.getChild("root");
        this.walk = WALK.get().bake(root);
        this.peek = PEEK.get().bake(root);
    }

    @Override
    public void setupAnim(MoleRenderState state) {
        // Resets every part to its rest pose. Everything below is additive.
        super.setupAnim(state);

        this.walk.applyWalk(state.walkAnimationPos, state.walkAnimationSpeed, 2.0F, 2.5F);

        // Secondary motion of the rearing pose: head sweep, snout twitch, paws.
        // The body angle deliberately is not part of this animation.
        this.peek.apply(state.peekAnimationState, state.ageInTicks);

        this.applyPeekPose(state.peekAmount);
    }

    /**
     * Tips the whole mole back by a fraction of the configured angle.
     *
     * <p>Kept out of the keyframe animation on purpose. A keyframe channel on
     * the root has to survive three separate coordinate conversions between
     * Blockbench and the game, which makes it near impossible to reason about.
     * Here the numbers mean exactly what they say, in model space, and they come
     * from {@link MoleDebug}, so they can be tuned with /moleverse peek while
     * looking straight at the mole.</p>
     *
     * @param amount 0 while crawling, 1 while fully reared up
     */
    private void applyPeekPose(float amount) {
        if (amount <= 0.001F) {
            return;
        }

        this.moleRoot.xRot += amount * (float) Math.toRadians(MoleDebug.peekPitchDegrees);
        this.moleRoot.y += amount * MoleDebug.peekOffsetY;
        this.moleRoot.z += amount * MoleDebug.peekOffsetZ;
    }

    // --- generated by Blockbench, do not edit ------------------------------
    // The root pivot sits at the hips, not at the centre of the body. Rearing
    // up rotates around that point, which is what keeps the mole in place
    // instead of swinging it through the ground.
    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition root = partdefinition.addOrReplaceChild("root", CubeListBuilder.create(),
                PartPose.offset(0.0F, 22.0F, 4.5F));

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-3.5F, -3.0F, -1.0F, 7.0F, 6.0F, 6.0F, new CubeDeformation(0.0F))
                .texOffs(0, 12).addBox(-3.0F, -2.5F, -5.0F, 6.0F, 5.0F, 4.0F, new CubeDeformation(0.0F)),
                PartPose.offset(0.0F, -3.0F, -3.5F));

        body.addOrReplaceChild("tail", CubeListBuilder.create()
                .texOffs(52, 15).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 4.0F, new CubeDeformation(0.0F)),
                PartPose.offset(0.0F, 0.0F, 4.0F));

        PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create()
                .texOffs(20, 12).addBox(-2.5F, -1.0F, -4.0F, 5.0F, 4.0F, 4.0F, new CubeDeformation(0.0F)),
                PartPose.offset(0.0F, -4.0F, -8.5F));

        head.addOrReplaceChild("snout", CubeListBuilder.create()
                .texOffs(38, 12).addBox(-1.5F, 0.0F, -4.0F, 3.0F, 2.0F, 4.0F, new CubeDeformation(0.0F))
                .texOffs(52, 12).addBox(-1.0F, 0.5F, -5.0F, 2.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)),
                PartPose.offset(0.0F, 0.0F, -3.0F));

        PartDefinition frontLegRight = root.addOrReplaceChild("front_leg_right", CubeListBuilder.create()
                .texOffs(0, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)),
                PartPose.offset(-3.5F, -4.0F, -6.5F));

        frontLegRight.addOrReplaceChild("front_paw_right", CubeListBuilder.create()
                .texOffs(26, 0).addBox(-3.0F, 0.0F, -3.0F, 4.0F, 2.0F, 5.0F, new CubeDeformation(0.0F))
                .texOffs(26, 7).addBox(0.0F, 0.5F, -5.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
                .texOffs(32, 7).addBox(-1.5F, 0.5F, -5.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
                .texOffs(38, 7).addBox(-3.0F, 0.5F, -5.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)),
                PartPose.offsetAndRotation(0.0F, 3.0F, 0.0F, 0.0F, 0.3142F, -0.2094F));

        PartDefinition frontLegLeft = root.addOrReplaceChild("front_leg_left", CubeListBuilder.create()
                .texOffs(8, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F)),
                PartPose.offset(3.5F, -4.0F, -6.5F));

        frontLegLeft.addOrReplaceChild("front_paw_left", CubeListBuilder.create()
                .texOffs(44, 0).addBox(-1.0F, 0.0F, -3.0F, 4.0F, 2.0F, 5.0F, new CubeDeformation(0.0F))
                .texOffs(44, 7).addBox(-1.0F, 0.5F, -5.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
                .texOffs(50, 7).addBox(0.5F, 0.5F, -5.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F))
                .texOffs(56, 7).addBox(2.0F, 0.5F, -5.0F, 1.0F, 1.0F, 2.0F, new CubeDeformation(0.0F)),
                PartPose.offsetAndRotation(0.0F, 3.0F, 0.0F, 0.0F, -0.3142F, 0.2094F));

        root.addOrReplaceChild("hind_leg_right", CubeListBuilder.create()
                .texOffs(16, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F))
                .texOffs(32, 21).addBox(-1.0F, 3.0F, -1.0F, 2.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
                PartPose.offset(-3.5F, -2.0F, -0.5F));

        root.addOrReplaceChild("hind_leg_left", CubeListBuilder.create()
                .texOffs(24, 21).addBox(-1.0F, 0.0F, -1.0F, 2.0F, 3.0F, 2.0F, new CubeDeformation(0.0F))
                .texOffs(42, 21).addBox(-1.0F, 3.0F, -1.0F, 2.0F, 1.0F, 3.0F, new CubeDeformation(0.0F)),
                PartPose.offset(3.5F, -2.0F, -0.5F));

        return LayerDefinition.create(meshdefinition, 64, 32);
    }
}
